block/blip

- plan/plan_loader.go
- plan/plan_loader_test.go
The `blip.Plan` returned by `PlanLoader.Plan` was a shallow copy. Which introduces the behavior where duplicate metrics are created when `ChangePlan` is called more than once. Using a deep copy fixes this issue.
> plan/plan_loader: return deep copy of blip.Plan from Plan

- dbconn/mycnf.go
- dbconn/mycnf_test.go
Got access denied error when providing cnf file for blip config. Fix it by parsing password from cnf file
Pointed to local blip for testing and access denied error was gone.
> Parse password from cnf file

- metrics/event.trx/trx.go
- metrics/factory.go
Add `event.trx` domain which contains `oldest` metric
Jira ticket: https://jira.sqprod.co/browse/SPIN-3539
Tested against my local mysql
1. add config files:
blip.yaml
```
plans:
files:
- plan.yaml
monitors:
- id: test1
hostname: 127.0.0.1
username: blip
meta:
repl-source: 127.0.0.1
```
plan.yaml
```
---
performance:
freq: 5s
collect:
event.trx:
metrics:
- oldest
```
2. run blip
```
cd ./blip/bin/blip
./blip
```
3. Blip print following line
```
blip 0.0.0
in 412.404µs: map[event.trx:[{Name:oldest Value:0 Type:2 Group:map[] Meta:map[]}]]
```
> Add event.trx collector

- config.go
- config_test.go
Environment variables referenced in the configuration file such as ${MYSQL_PASSWORD} were not properly interpolated if they contained a dollar sign $ character. These are now handled correctly.
> Fix configuration env interpolation with special characters

- monitor/loader.go
- monitor/loader_test.go
- monitor/monitor.go
- monitor/monitor_test.go
TransformMetrics is not set in LevelCollector so it cannot be invoked to convert metrics even it is specified by the client. This change is to pass TransformMetrics down to LevelCollector. 
Pointed to my local blip change and tested against test metacluster node with TransformMetrics configuration
> Pass TransformMetrics down to LevelCollector

- metrics/repl/repl.go
repl.running should determine its value based on `Replica_IO_Running` and `Replica_SQL_Running` for mysql 8.0
Pointed to local blip change and tested again my test metacluster node
> Fix repl.running issue for mysql 8.0

- server/server.go
- sink/signalfx.go
Setup http client timeout when creating sink client and close idle connection after a sfx error to fix no datapoints issue in sfx for ~6min.
Tested against test cluster nodes
> Setup sink client timeout and close idle connections for sfx

- monitor/monitor.go
This is to fix the issue that it returns nil instead of keeping retry when encountering an error for DB maker, like failing to read mycnf file. 
Tested against test metacluster
> Keep retry when there is the error to make DB

- monitor/engine.go
- monitor/level_collector.go
- server/api.go
Adding code to reload monitors via the API. Per comments in `loader.go` above `StartMonitors` it _seems_ like this functionality should exist. `loader.Load` supports detecting diffs in monitors but there is no hook from the API to run `Load` then `StartMonitors`.
Added a `Stop` function to `Engine` to facilitate cleaning up metrics when a monitor stops. The level collector has code that runs when a monitor stops but no cleanup on the engine, and the metrics it contains, is ever run. This leaves a heartbeat reader hanging for old monitors using the `repl.lag` metric.
The goal of adding this API endpoint is to facilitate the use of `plugins.LoadMonitors` where the plugin can dynamically update the monitors that need to run. Once the plugin updates the list of monitors it can invoke the …
> Add monitor reloading

- config.go
- dbconn/factory.go
- dbconn/reload_password.go
Added support for full credentials (username, password, and/or TLS config) to DSN reload for driver. In some cases we have the contents of a CNF file updated with both new credentials and a new user name, and possibly updated certs. This supports that case while preserving the original functionality around a fixed username and rotated passwords.
This doest _not_ support turning TLS on/off dynamically. This approach assumes that once we choose to use TLS for a monitor that we will continue to do so, and we will only rotate the certs.
>  Hotswappable Credentials

- config.go
- docs/v1.0/config/config-file.md
- monitor/monitor.go
Adding `Plan` to `ConfigMonitor` to allow configuration of the plan by name rather than by load order, which is the default behavior for `Plan = ""`. This is only used if `ConfigMonitor.Plans.Adjust` is not configured.
Updated documentation with some basic info to keep track of this addition.
> Adding Plan Selection to Config

- metrics/size.database/database.go
The "total" option, when enabled, sends a metric but the value of the metric is never set.
> Bugfix for `size.database`

- blip.go
- config.go
- config_test.go
- server/api.go
- server/server.go
* Test API bind on config validation (while booting)
* 1s sleep between API crashes
> Clarify LoadConfig and defaults

- docs/v1.0/sinks/datadog.md
- sink/datadog.go
- sink/datadog_test.go
- test/mock/http.go
- test/mock/tr.go
Added options for compression and partitioning to the Datadog sink when the API method is used. When receiving an error related to the payload size being too large the sink will attempt to calculate a possible size that will satisfy the size requirements and re-send the metrics. In the event that it exhausts options and cannot send the metrics the attempt will fail.
Added the option to turn on compression for the API, which allows much larger payloads by default.
> Adding Partitioning to Datadog Sink

- sink/datadog.go
In certain (unknown) cases, submitting metrics via the Datadog API fails with the error `EOF` and a `nil` http response. It appears that while the Datadog API config has a `Compress` field, setting it to `true` does not actually enable compression. It only prevents it from disabling compression:
```golang
if !c.Cfg.Compress {
// gzip is on by default, so disable it by setting encoding to identity
localVarRequest.Header.Add("Accept-Encoding", "identity")
}
```
Despite the Datadog client indicating the gzip compression is on by default, an inspection of the code and dumping the request indicates that it is not. Manually setting the content encoding on each request is required to actually enable compression.
In some case the lack of compression caused a failure in the underlying http client …
> Fixing intermittent panic on metric submission

- metrics/repl/repl.go
Moved the package-level variables `statusQuery` and `newTerms` to the monitor in case multiple monitors within the same domain are created but are running on different MySQL versions.
Added a check around `replStatus` when getting the "source" entry. In cases where something is not a replica the map will be nil and should not be accessed.
> Moving Package Variable to Monitor

- sink/datadog.go
- sink/datadog_test.go
Related to #93
Updated unit tests, as now that compression is _actually_ working the client compresses the data for us in the unit test.
> Missed adding the parameter variable

- sink/datadog.go
Aurora metrics are failing in datadog sink because the timestamps are in `ms` and datadog expects them in `seconds`.
I am converting the the `ts` to seconds to fix the missing metrics.
There's more work to be done in terms of error handling in the sink. I will raise a different PR for other changes. Want to fix the missing metrics first.
> Convert ts from ms to seconds in datadog sink

- event/list.go
- sink/datadog.go
- sink/datadog_test.go
Datadog can return a `202 Accepted` response code but errors in response payload. This PR adds a check for that.
From what it looks like, the endpoint probably also partially accept MetricData which are valid and return errors for invalid ones.
With this, we will at least see in logs what's going on and will be able to fix it quickly. Without this, it was failing silently.
> Add error handling for errors in Datadog API response

- docs/v1.0/metrics/domains.md
- errors/truncate_error.go
- errors/truncate_error_test.go
- metrics/query.response-time/response_time.go
- metrics/wait.io.table/table.go
Added timeouts on truncation operations for `query.response-time` and `wait.io.table`. In MySQL [locking an instance for backup](https://dev.mysql.com/doc/refman/8.0/en/lock-instance-for-backup.html) will cause `TRUNCATE` to block. This will cause multiple instances of the command to stack up, driving up the thread count on the server. A default timeout of `2s` has been set and is configurable by the user. An error, `truncate-failed` has also been setup to allow users to specify an error handling strategy in the event that `TRUNCATE` fails.
> Truncation Timeouts

- metrics/status.global/global.go
Changing the type of `status.max_used_connections` to gauge.
As we are sending delta for counter metrics now, after a certain period of time most (if not all) data points for this metric will be `0`.
So changing it to gauge instead, we can use `max` as rollup function.
> Change type of status.max_used_connections to gauge

- config.go
- docker-compose.yaml
- monitor/engine.go
- monitor/level_collector.go
- monitor/level_collector_test.go
- monitor/monitor.go
- monitor/mysqld_exporter.go
- sink/datadog.go
- sink/datadog_test.go
- sink/delta.go
- sink/delta_test.go
- sink/factory.go
- sink/retry.go
- sink/retry_test.go
- sink/signalfx.go
- test/mock/metrics.go
- test/plans/lpc_2_domains.yaml
Ian's original PR works around engine v1 problems using fully asynchronous metrics collections from collectors to sinks. Engine v2 will scope this down to preserve synchronous calls were possible, so I'll modify this code after merging. But I wanted to start with this code because it also has various code fixes we need.
> Initialize engine v2 with Ian's original PR

- metrics/repl.lag/lag.go
- metrics/repl.lag/lag_test.go
- metrics/repl.lag/pfs.go
- test/docker/docker-compose.yaml
- test/plans/default.yaml
This follows the same pattern `var.global` uses to add options for collecting replication lag from performance schema.
I haven't updated the doc yet, as it seems current `repl.log` collector usage is documented in `Heartbeat` section, it probably doesn't make sense to add the `pfs` option in that page. So we have to restructure the doc a bit to document this update.
> Update repl.lag collector to add option for collecting lag using performance schema

- SECURITY.md
- blip.go
- go.mod
- go.sum
* Bump version to v1.1.0
* Update SECURITY.md
* Update Go MySQL driver
[Docs](https://cashapp.github.io/blip/) have already been updated and published.
> Release v1.1.0

- docs/content/api/blip.md
- docs/content/config/blip.md
- docs/content/config/logging.md
- server/api.go
- server/server.go
This PR adds 2 things:
1. a new `/debug` API endpoint which toggles blip.Debugging. it returns a string telling you whether it's been enabled or disabled.
2. a signal listener on `SIGUSR1` that toggles blip.Debugging. this will write to stderr whether it's turned debugging on or off.
I figured it might be helpful to support both of these. In a k8s context, it might be more simple to send a signal to the process running in the container than to figure out where its API endpoint is listening.
> add debug API endpoint and signal listener

- metrics/query.response-time/response_time.go
`query.response-time` relies on the ordering of results based on `bucket_quantile` but in some cases there are multiple rows with the same value for `bucket_quantile`. This results in undefined behavior as we don't know which of the rows returned will be chosen for the `LIMIT 1`. Usually the results are ordered by the natural order of the table (e.g. `bucket_number`) which produces expected behavior but occasionaly this isn't the case and anomalous values are returned as the latency. Adding an explicit ordering on `bucket_number` in addition to `bucket_quantile` should resolve this issue.
> Force Order for Query Latency

- dbconn/factory.go
- dbconn/factory_test.go
- heartbeat/reader.go
- heartbeat/writer.go
- metrics/innodb/innodb.go
- metrics/repl.lag/lag.go
- metrics/size.database/database.go
- metrics/size.database/query.go
- metrics/size.database/query_test.go
- metrics/size.table/query.go
- metrics/size.table/query_test.go
- metrics/size.table/table.go
- metrics/var.global/global.go
- metrics/var.global/global_test.go
- metrics/wait.io.table/query.go
- metrics/wait.io.table/query_test.go
- metrics/wait.io.table/table.go
- sqlutil/sqlutil.go
- sqlutil/sqlutil_test.go
- test/mysql.go
`sqlutil.INList` repeats the first value of the list and leaves the last value off the resulting string. Fixed this bug and replaced uses of unescaped `IN` list creation with calls to `sqlutil.INList` where appropriate.
Adjusted metrics and heartbeat to use driver-level parameter interpolation instead of custom escaping, deprecating several function in `sqlutil`. Removed the use of `sqlutil.INList` in existing blip code but marked as deprecated.
> Fix `sqlutil.INList`

- docs/content/metrics/domains/error.account/_index.md
- docs/content/metrics/domains/error.global/_index.md
- docs/content/metrics/domains/error.host/_index.md
- docs/content/metrics/domains/error.thread/_index.md
- docs/content/metrics/domains/error.user/_index.md
- docs/content/metrics/domains/innodb.buffer-pool/_index.md
- docs/content/metrics/domains/innodb/_index.md
- docs/content/metrics/quick-ref.md
- go.mod
- go.sum
- metrics/error/account.go
- metrics/error/error.go
- metrics/error/global.go
- metrics/error/host.go
- metrics/error/query.go
- metrics/error/query_test.go
- metrics/error/thread.go
- metrics/error/user.go
- metrics/factory.go
- metrics/size.database/database.go
- sqlutil/sqlutil.go
Adding the `metrics/error` package that includes the following domains:
- `error.global`
- `error.account`
- `error.host`
- `error.thread`
- `error.user`
These domains emit metrics on errors from the error summary tables (https://dev.mysql.com/doc/refman/en/performance-schema-error-summary-tables.html) See the documentation for more details.
> Adding the `error.*` domains

- CHANGES.md
- CONTRIBUTING.md
- README.md
- RELEASE.md
- blip.go
- collector.go
- docs/content/about/release-notes.md
- examples/copy-meta/README.md
- examples/integrate/README.md
- monitor/level_collector.go
- plan/loader.go
The repo was moved from the CashApp Github Org. This PR fixes doc links by updating them to the new Block domain.
> Update github docs to Block domain

- aws/secret.go
- dbconn/factory.go
Update to the hotswap credentials function. Changes the logic for the `password-secret` authentication mode. Retrieves a `username` key in addition to `password` and if found sets the mysql config.
> Retrieve username from secret in the hotswap driver function
